[package]
name = "html2text_rs_py"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "html2text_rs_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
rayon = "1.7.0"
html2text = "0.6.0"
walkdir = "2.3.2"
anyhow = "1.0.44"
clap = { version = "4.5.37", features = ["derive"] }
kuchiki = "0.8.1"

[profile.release]
opt-level = 3
lto = true
panic = 'abort'
debug = false
